<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HAAR0538" name="Regression1" tests="1" failures="1" timestamp="7 Sep 2021 20:08:53 GMT" time="37.181" errors="0">
  <testcase name="runScenario" time="29.849" classname="testrunner.TestRunner">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertFalse(Assert.java:39)
	at junit.framework.Assert.assertFalse(Assert.java:47)
	at stepdefinition.CAcceptpayment.val_accept_pay(CAcceptpayment.java:40)
	at âœ½.Validate Accept Payment page(file:///D:/PRODHATF/features/CheckinAsyst/Appointments/AcceptPayment.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Regression1 -->
